export default {
  APP_NAME: 'Otherly',

  // Pagination
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 30,
};

export enum Environment {
  DEVELOPMENT = 'DEVELOPMENT',
  PRODUCTION = 'PRODUCTION',
  TEST = 'TEST',
}

export enum MediaType {
  PRODUCT_IMAGE = 'PRODUCT_IMAGE',
  AVATAR = 'AVATAR',
  CATEGORY_ICON = 'CATEGORY_ICON',
  CATEGORY_BANNER = 'CATEGORY_BANNER',
  REQUEST_ATTACHMENT = 'REQUEST_ATTACHMENT',
  DOCUMENT = 'DOCUMENT',
}

export enum Role {
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  VENDOR = 'VENDOR',
  CUSTOMER = 'CUSTOMER',
}

export enum TokenEnum {
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  PASSWORD_RESET_TOKEN = 'PASSWORD_RESET_TOKEN',
  EMAIL_VERIFICATION_TOKEN = 'EMAIL_VERIFICATION_TOKEN',
}

export enum ContactTopic {
  PARTNERSHIP = 'Partnership',
  OUR_PRODUCTS = 'Our Products',
  INVESTMENT = 'Investment',
  OTHER = 'Other',
}

export enum ContactStatus {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  ARCHIVED = 'ARCHIVED',
}

export enum MailType {
  CONTACT_ADMIN_NOTIFICATION = 'CONTACT_ADMIN_NOTIFICATION',
  CONTACT_USER_ACKNOWLEDGEMENT = 'CONTACT_USER_ACKNOWLEDGEMENT',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
}

export enum EmailDeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  IN_REVIEW = 'IN_REVIEW',
  FULFILLED = 'FULFILLED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum OfferStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum OfferFulfillType {
  IN_STOCK = 'IN_STOCK',
  PARTIAL_STOCK = 'PARTIAL_STOCK',
  CAN_SOURCE = 'CAN_SOURCE',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum OrderSourceType {
  DIRECT_PURCHASE = 'DIRECT_PURCHASE',
  REQUEST_OFFER = 'REQUEST_OFFER',
}

export enum NotificationType {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  OFFER_REJECTED = 'OFFER_REJECTED',
  REQUEST_FULFILLED = 'REQUEST_FULFILLED',
  VENDOR_VERIFIED = 'VENDOR_VERIFIED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  GENERAL = 'GENERAL',
}
